### ISSUE TITLE
[FEATURE_REQUEST] walkxcode/dashboard-icons integration

### ISSUE THREAD

**Issue by FieldofClay** [knrdl/hubleys-dashboard#52]
Firstly, great app, exactly the type of dashboard I've been looking for!

It would be great to integrate [walkxcode/dashboard-icons](https://github.com/walkxcode/dashboard-icons) into Hubleys, so if the user can put in logo configuration like this:
```
  - title: Nextcloud
    url: https://nextcloud.com
    logo: di nextcloud.png
```
Hubley's would go and grab the icon (if it didn't exist in logos already), save it in logos, then use that as the logo. This same approach could be used with some other icon providers ([Simple Icons](https://simpleicons.org/), [Material Icons](https://github.com/Templarian/MaterialDesign) etc) and would speed up the initial configuration process for new users.

Alternatively, an easier option would be to just link to them as sources for icons for new users to download themselves.

**Comment by knrdl** [comment]
Thanks for your feedback! I would for the sake of simplicity just reference the icon sets in the docs: see https://github.com/knrdl/hubleys-dashboard/commit/b695f1de1d47f39e5f7234be7a78305365b852ab
Otherwise there would be a need for a real form of integration (like an interactive icon browser) to take advantage of this feature.  But that is definitely out of scope for now, sorry.

**Comment by FieldofClay** [comment]
No worries. Looks good, and no need for the shout out. 

Also, handy point that you can use URLs instead of the file name.
